<?php

function event_list_menu() {
    $items['event_list'] = array(                       //item 中的參數名為路徑
        'title' => '活動登記申請',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('event_list_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,   //MENU_NORMAL_ITEM  MENU_CALLBACK
    );

    return $items;
}

function event_list_form($form,&$form_state) {

    $form['event_title'] = array(
        '#type' => 'textfield',
        '#title' => t('活動名稱：'),
        '#required' => TRUE,
        '#default_value' => "",
//        '#element_validate' => array('_input_max_number'),
        '#size' => 10,
        '#maxlength' => 10,
    );
    $form['event_subject'] = array(
        '#type' => 'textfield',
        '#title' => t('活動主旨：'),
        '#required' => TRUE,
        '#default_value' => "",
//        '#element_validate' => array('_input_max_number'),
        '#size' => 10,
        '#maxlength' => 10,
    );
    $form['event_content'] = array(
        '#type' => 'textarea',
        '#title' => t('活動內容：'),
        '#required' => TRUE,
        '#default_value' => "請輸入詳細活動名稱",

    );

    $time = REQUEST_TIME;

    $date = '2008-12-31 00:00:00';
    $format = 'Y-m-d H:i';
    $form['event_start_signin_time'] = array(
        '#type' => 'date_popup', // types date_select 'date_popup', 'date_text' and 'date_timezone' are also supported. See .inc file.
        '#title' => t('活動報名開始時間：'),
        '#default_value' => date($format, $_SERVER['REQUEST_TIME']),                                                    //預設時間
        '#date_format' => $format,
        '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
        '#date_timezone' => 'asia/taipei', // Optional, if your date has a timezone other than the site timezone.
        '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
        '#date_year_range' => '-0:+1', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
        '#datepicker_options' => array(), // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
    );

    $form['event_end_signin_time'] = array(
        '#type' => 'date_popup', // types date_select 'date_popup', 'date_text' and 'date_timezone' are also supported. See .inc file.
        '#title' => t('活動報名截止時間：'),
        '#default_value' => date($format, $_SERVER['REQUEST_TIME']),                                                    //預設時間
        '#date_format' => $format,
        '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
        '#date_timezone' => 'asia/taipei', // Optional, if your date has a timezone other than the site timezone.
        '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
        '#date_year_range' => '-0:+1', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
        '#datepicker_options' => array(), // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
    );

    $form['event_start_time'] = array(
        '#type' => 'date_popup', // types date_select 'date_popup', 'date_text' and 'date_timezone' are also supported. See .inc file.
        '#title' => t('活動開始時間：'),
        '#default_value' => date($format, $_SERVER['REQUEST_TIME']),                                                    //預設時間
        '#date_format' => $format,
        '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
        '#date_timezone' => 'asia/taipei', // Optional, if your date has a timezone other than the site timezone.
        '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
        '#date_year_range' => '-0:+1', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
        '#datepicker_options' => array(), // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
    );
    $form['event_end_time'] = array(
        '#type' => 'date_popup', // types date_select 'date_popup', 'date_text' and 'date_timezone' are also supported. See .inc file.
        '#title' => t('活動結束時間：'),
        '#default_value' => date($format, $_SERVER['REQUEST_TIME']),                                                    //預設時間
        '#date_format' => $format,
        '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
        '#date_timezone' => 'asia/taipei', // Optional, if your date has a timezone other than the site timezone.
        '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
        '#date_year_range' => '-0:+1', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
        '#datepicker_options' => array(), // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
    );



    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;


    //return 'How are you !';
}
//
//function _input_max_number($element, &$form_state){   //較為好的限制方法 因為其可以自行對應$element
//
//    $check_number=$element['#value'];
//    dpm($element);
//    if($check_number=='0') {
//
//    }else if(((int)$check_number) == 0){
//        form_error($element, t('請輸入整數數字!'));      //輸入正確的$element 在錯誤時會提醒使用者位置
//
//    }else if(((int)$check_number>=500 ) || ((int)$check_number <=0)){
//        form_error($element, t('請輸入500-0之間的數字'));
//
//    }
//}




//
//
//
//function starting_drupal_dev_form_validate($form, &$form_state) { //處理例外限制
//
//
//    $check_number=$form_state['values']['mitter_good']['one'];
//    dpm($form_state['values']['mitter_good']);
//
//
//    if($check_number=='0') {
//
//    }else if(((int)$check_number) == 0){
//        //mitter_good][one 為當該格錯誤時 會提醒使用者錯誤位置
//        // 由於本結構分為兩階 所以在階層中分為 [mitter_good][one] 中間用][連結
//        form_set_error('mitter_good][one', t('請輸入整數數字!'));
//
//
//    }else if(((int)$check_number>=500 ) || ((int)$check_number <=0)){
//        form_set_error('mitter_good][one', t('請輸入500-0之間的數字'));
//
//    }
//}
//
function event_list_form_submit($form, &$form_state) { // 按下 SUBMIT 後，處理數據




    $noed = node_type_load("event");
    dpm($form_state);
    dpm($form_state['values']['event_subject']);

    $new = new stdClass();
    $new->type = "event";
    $new->language = LANGUAGE_NONE;

    $new->title =  $form_state['values']['event_title'] ;


    $new->field_event_subject[LANGUAGE_NONE][0]['value'] = $form_state['values']['event_subject'];
    $new->body[LANGUAGE_NONE][0]['value'] =  $form_state['values']['event_content'] ;
    $new->field_event_start_signin_time[LANGUAGE_NONE][0]['value'] = strtotime($form_state['values']['event_start_signin_time']);


    $new->field_event_end_signin_time[LANGUAGE_NONE][0]['value'] =  strtotime($form_state['values']['event_end_signin_time']) ;
    $new->field_event_start_time[LANGUAGE_NONE][0]['value'] =  strtotime($form_state['values']['event_start_time']) ;
    $new->	field_event_end_time[LANGUAGE_NONE][0]['value'] =  strtotime($form_state['values']['event_end_time']) ;

    node_object_prepare($new);              //才有登入狀態
    node_save($new);



//    $new->type = "event";
//    $new->language = LANGUAGE_NONE;
//    node_object_prepare($new);
//
//    $new->field_event_time[LANGUAGE_NONE][0]['value'] = time();
//     $new->field_event_start_time[LANGUAGE_NONE][0]['value'] = strtotime('+1 month',REQUEST_TIME);
//    node_save($new);
//
//   $node = node_load(2);
//   dpm($node);
//   dpm($node->field_event_start_time[LANGUAGE_NONE][0]['value']);
//    $field_event_time = field_get_items('node',$node,'field_event_start_time',LANGUAGE_NONE);
//    dpm($field_event_time);
//
//    $radius = $form_state['values']['radius'];
//    $area = $radius * $radius * M_PI;
//
//    drupal_set_message($form); // Output ................etc

}


?>
