<?php

function event_list_menu() {
    $items['event_list'] = array(                       //item 中的參數名為路徑
        'title' => '活動申請',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('event_list_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,   //MENU_NORMAL_ITEM  MENU_CALLBACK
    );

    return $items;
}

function event_list_form($form,&$form_state) {

    $form['description'] = array(
        '#type' => 'item',
        '#title' => t('活動登記申請'),

    );

    $date = '2008-12-31 00:00:00';
    $format = 'Y-m-d H:i';

    $form['date2'] = array(
        '#type' => 'date_select', // types 'date_popup', 'date_text' and 'date_timezone' are also supported. See .inc file.
        '#title' => t('Date'),
        '#default_value' => $date,
        '#date_format' => $format,
        '#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
        '#date_timezone' => 'America/Chicago', // Optional, if your date has a timezone other than the site timezone.
        '#date_increment' => 15, // Optional, used by the date_select and date_popup elements to increment minutes and seconds.
        '#date_year_range' => '-3:+3', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
        '#datepicker_options' => array(), // Optional, as of 7.x-2.6+, used to pass in additional parameters from the jQuery Datepicker widget.
    );




    return $form;


    //return 'How are you !';
}
//
//function _input_max_number($element, &$form_state){   //較為好的限制方法 因為其可以自行對應$element
//
//    $check_number=$element['#value'];
//    dpm($element);
//    if($check_number=='0') {
//
//    }else if(((int)$check_number) == 0){
//        form_error($element, t('請輸入整數數字!'));      //輸入正確的$element 在錯誤時會提醒使用者位置
//
//    }else if(((int)$check_number>=500 ) || ((int)$check_number <=0)){
//        form_error($element, t('請輸入500-0之間的數字'));
//
//    }
//}




//
//
//
//function starting_drupal_dev_form_validate($form, &$form_state) { //處理例外限制
//
//
//    $check_number=$form_state['values']['mitter_good']['one'];
//    dpm($form_state['values']['mitter_good']);
//
//
//    if($check_number=='0') {
//
//    }else if(((int)$check_number) == 0){
//        //mitter_good][one 為當該格錯誤時 會提醒使用者錯誤位置
//        // 由於本結構分為兩階 所以在階層中分為 [mitter_good][one] 中間用][連結
//        form_set_error('mitter_good][one', t('請輸入整數數字!'));
//
//
//    }else if(((int)$check_number>=500 ) || ((int)$check_number <=0)){
//        form_set_error('mitter_good][one', t('請輸入500-0之間的數字'));
//
//    }
//}
//
//function mitter_form_submit($form, &$form_state) { // 按下 SUBMIT 後，處理數據
//
//    dpm($form_state);
////
////
////    $radius = $form_state['values']['radius'];
////    $area = $radius * $radius * M_PI;
//
//    drupal_set_message($form); // Output ................etc
//
//}


?>
