<?php // $Id$
/**
 * @file
 * cat_manger module file
 *
 * This module allows site administrators to send a stock warning
 * e-mail to a specified user or users through the admin interface.
 * Administrators
 * can configure the default e-mail including token replacement.
 */
/**
 * Implement hook_help().
 */
function cat_manger_help($path, $arg)
{
    if ($path == 'admin/help#cat_manger') {
        return t('管理介面練習用 此行會在module說明頁顯示.');
    }
}


/**
 * Implement hook_menu().
 */
function cat_manger_menu()
{
    $items = array();
    $items['admin/config/people/cat_manger'] = array(                   //網址 其中網址前面的路徑會決定此項被放在管理目錄的位置
        'title' => '管理貓群',                                          //控制這項的標題
        'description' => '管理貓群的活動',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cat_manger_form'),
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,

    );

    $items['user/%/cat_manger'] = array(
        'title' => '提醒牠',
        'description' =>
            '提醒他該出現囉！.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cat_manger_confirm_form', 1),
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
    );
    return $items;
}


///**
// * Form builder; Create and display the User Warn configuration
// * settings form.
// */
//function cat_manger_form($form, &$form_state) {
//    // Text field for the e-mail subject.
//    global $user;
//    dpm($user);
//    $form['cat_manger_e-mail_subject'] = array(
//        '#type' => 'textfield',
//        '#default_value' => variable_get('cat_manger_e-mail_subject','Administrative Warning'),         //檢查前項有沒有在全域變數中 否則貼上後者
//        '#title' => t('信件標題'),
//        '#description' => t('標題'),
//        '#size' => 40,
//        '#maxlength' => 120,
//        '#required' => TRUE,
//    );
//    define('cat_manger_MAIL_TEXT',
//        'Hello,
//   We have been notified that you have posted comments on our site that
//   are in violation of our terms of service.  If this behavior continues
//   your account will be suspended.
//   Sincerely,
//   The administrative staff');
//    // Textarea for the body of the e-mail.
//    $form['cat_manger_e-mail_text'] = array(
//        '#type' => 'textarea',
//        '#default_value' => variable_get('cat_manger_e-mail_text',
//            cat_manger_MAIL_TEXT),
//        '#rows' => 10,
//        '#columns' => 40,
//        '#title' => t('e-mail text'),
//        '#required' => TRUE,
//        '#description' => t('內文'),
//    );
//    // Checkbox to indicate if admin should be sent a Bcc on e-mails.
//    $form['cat_manger_bcc'] = array(
//        '#type' => 'checkbox',
//        '#title' => t('BCC admin on all e-mails'),
//        '#default_value' => variable_get('cat_manger_bcc', FALSE),
//        '#description' => t("Indicates whether the admin user (as set in
//   site configuration) should be sent on all warning e-mails."),
//    );
//    // Submit button
//    $form['submit'] = array(
//
//        '#type' => 'submit',
//        '#value' => t('Save settings'),
//
//    );
//    return $form;
//}


/**
 * Form builder; Build the User Warn settings form.
 */
function cat_manger_form($form, &$form_state) {
    // Text field for the e-mail subject.
    $form['cat_manger_e-mail_subject'] = array(
        '#type' => 'textfield',
        '#default_value' => 'Administrative Warning',
        '#title' => t('Warning e-mail subject'),
        '#size' => 40,
        '#maxlength' => 120,
        '#required' => TRUE,
        '#description' => t(
            'The subject of the e-mail which will be sent to users.'),
    );
        define('cat_manger_MAIL_TEXT',
        'Hello,[user:name]
   We have been notified that you have posted comments on our site that
   are in violation of our terms of service.  If this behavior continues
   your account will be suspended.
   Sincerely,
   The administrative staff');
    // Textarea for the body of the e-mail.
    $form['cat_manger_e-mail_text'] = array(
        '#type' => 'textarea',
        '#rows' => 10,
        '#columns' => 40,
        '#default_value' => cat_manger_MAIL_TEXT, '#title' => t('Warning e-mail text'), '#required' => TRUE,
        '#description' => t(
            'The text of the e-mail which will be sent to users.'),
    );
    // Checkbox to indicate whether admin should be sent a Bcc
    // on e-mails.
    $form['cat_manger_bcc'] = array(
        '#type' => 'checkbox',
        '#default_value' => FALSE,
        '#title' => t('BCC admin on all e-mails'),
        '#description' => t('Indicates whether the admin user (as set in
   site configuration) should be BCC\'d on all warning e-mails.'),
    );
    return system_settings_form($form);
}

/**
 * Form builder; display the e-mail confirmation form.
 */
function cat_manger_confirm_form($form, &$form_state, $uid)
{
    $form['account'] = array(
        '#type' => 'value',
        '#value' => user_load($uid),
    );

    return confirm_form(
        $form,
        t(
            'Are you sure you want to send a warning e-mail to this user?'),
        'user/' . $uid,
        t('This action can not be undone.'),
        t('Send e-mail'),
        t('Cancel')
    );
}





//
///**
// * Form builder; display the e-mail confirmation form.
// */
//function cat_manger_confirm_form($form, &$form_state, $uid) {
//    $form['account'] = array(
//        '#type' => 'value',
//        '#value' => user_load($uid),
//    );
//    return confirm_form(
//        $form,
//        t('Are you sure you want to send a warning e-mail to this
//       user?'),
//        'user/' . $uid,
//        t('This action can not be undone.'),
//        t('Send e-mail'),
//        t('Cancel')
//    ); }


/**
 * Save configuration settings for User Warn module.
 */
function cat_manger_form_submit($form, &$form_state)
{

    $account = $form_state['values']['account'];
    drupal_mail(
        'cat_manger',
        'cat',
        $account->mail,
        user_preferred_language($account),
        $form_state['values'],
        variable_get('site_mail', NULL),
        TRUE
    );



//
//    variable_set('cat_manger_e-mail_subject',
//        $form_state['values']['cat_manger_e-mail_subject']);
//    variable_set('cat_manger_e-mail_text',
//        $form_state['values']['cat_manger_e-mail_text']);
//    variable_set('cat_manger_bcc',
//        $form_state['values']['cat_manger_bcc']);
//    drupal_set_message(t('The settings have been saved'));
}
///**
// * Implement hook_mail().
// */
//function cat_manger_mail($key, &$message, $params) {
//    switch ($key) {
//        case 'cat':
//            $account = $params['account'];
//            $subject = variable_get('cat_manger_e-mail_subject',
//                'Administrative Warning');
//            $body = variable_get('cat_manger_e-mail_text',
//                'You\'ve been warned!');
//            if (variable_get('cat_manger_bcc', FALSE)) {
//                $admin_mail = variable_get('site_mail', NULL);
//                $message['headers']['bcc'] = $admin_mail;
//            }
//            $message['to'] = $account->mail;
//            $message['subject'] = $subject;
//            $message['body'][] = $body;
//            break;
//    } }
/**
 * Implement hook_mail().
 */
function cat_manger_mail($key, &$message, $params) {
    switch ($key) {
        case 'cat':
            $account = $params['account'];
            $subject = variable_get('cat_manger_e-mail_
   subject','Administrative Warning');
            $body = variable_get('cat_manger_e-mail_text',
                cat_manger_MAIL_TEXT);
            if (variable_get('cat_manger_bcc', FALSE)) {
                $admin_mail = variable_get('site_mail', NULL);
                $message['headers']['bcc'] = $admin_mail;
            }
            $message['to'] = $account->mail;
            $message['subject'] = $subject;
            $message['body'][] = token_replace($body,
                array('user' => $account));
            break; }
}

