<?php


function bigcat($item)
{

    dpm($item);
    dpm(t('here is bigcat!'));
    //module_invoke_all('eat_number');
    return $item;
}


/**
 * Implements hook_menu().
 *
 * Here we set up the URLs (menu entries) for the
 * form examples. Note that most of the menu items
 * have page callbacks and page arguments set, with
 * page arguments set to be functions in external files.
 */
function bigcat_menu()
{
    $items = array();
    $items['test/test1'] = array(
        'title' => 'Form Example',
        'page callback' => 'form_example_intro',
        'access callback' => TRUE,
        'expanded' => TRUE,
    );

    $items['test/test1/tutorial'] = array(
        'title' => 'Form Tutorial',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_example_tutorial_1'),
        'access callback' => TRUE,
        'description' => 'A set of ten tutorials',
        'file' => 'form_example_tutorial.inc',
        'type' => MENU_NORMAL_ITEM,
    );


    $items['test/test1/tutorial/2'] = array(
        'title' => '#2',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_example_tutorial_2'),
        'access callback' => TRUE,
        'description' => 'Tutorial 2: Form with a submit button',
        'type' => MENU_LOCAL_TASK,
        'file' => 'form_example_tutorial.inc',
    );
}

/**
 * Page callback for our general info page.
 */
function bigcat_intro() {
    $markup = t('The form example module provides a tutorial, extensible multistep example, an element example, and a #states example');
    return array('#markup' => $markup);
}


/**
 * Implements hook_help().
 */
function bigcat_help($path, $arg) {
    switch ($path) {
        case 'test/test1/tutorial':
            // TODO: Update the URL.
            $help = t('This form example tutorial for Drupal 7 is the code from the <a href="http://drupal.org/node/262422">Handbook 10-step tutorial</a>');
            break;
        case 'test/test1/element_example':
            $help = t('The Element Example shows how modules can provide their own Form API element types. Four different element types are demonstrated.');
            break;
    }
    if (!empty($help)) {
        return '<p>' . $help . '</p>';
    }
}






?>
